-- Seed Data for Property Management Tabs
-- This file seeds data for Amenities, Images, Floor Plans, Maintenance Schedules, and Vendors

-- ============================================
-- VENDORS (Global - not property-specific)
-- ============================================
INSERT INTO vendors (name, company_name, email, phone, mobile, address, city, state, zip_code, website, license_number, insurance_info, tax_id, rating, hourly_rate, emergency_contact, availability, total_jobs, average_cost, notes, is_preferred, is_active, created_at)
VALUES 
    ('TechFix Solutions', 'TechFix Solutions LLC', 'contact@techfix.com', '0901234567', '0901234568', '123 Tech Street, District 1', 'Ho Chi Minh City', 'Ho Chi Minh', '70000', 'https://techfix.com', 'LIC-2024-001', 'Insured up to $1M', 'TAX-123456', 4.8, 500000, '0901234569', '24/7 Emergency Service', 150, 2500000, 'Reliable HVAC and electrical services', true, true, NOW() - INTERVAL '90 days'),
    ('PlumbPro Services', 'PlumbPro Services Co.', 'info@plumbpro.com', '0902345678', '0902345679', '456 Water Lane, District 2', 'Ho Chi Minh City', 'Ho Chi Minh', '70000', 'https://plumbpro.com', 'LIC-2024-002', 'Fully insured', 'TAX-234567', 4.6, 400000, '0902345680', 'Mon-Sat 8AM-6PM', 120, 1800000, 'Expert plumbing and water system maintenance', true, true, NOW() - INTERVAL '75 days'),
    ('Elevator Experts', 'Elevator Experts Inc.', 'service@elevatorexperts.com', '0903456789', '0903456790', '789 Lift Avenue, District 3', 'Ho Chi Minh City', 'Ho Chi Minh', '70000', 'https://elevatorexperts.com', 'LIC-2024-003', 'Insured', 'TAX-345678', 4.9, 800000, '0903456791', '24/7 Emergency', 80, 5000000, 'Specialized elevator maintenance and repair', true, true, NOW() - INTERVAL '60 days'),
    ('SafeGuard Security', 'SafeGuard Security Systems', 'sales@safeguard.com', '0904567890', '0904567891', '321 Safety Road, District 7', 'Ho Chi Minh City', 'Ho Chi Minh', '70000', 'https://safeguard.com', 'LIC-2024-004', 'Insured', 'TAX-456789', 4.7, 600000, '0904567892', 'Mon-Fri 9AM-5PM', 95, 3500000, 'Fire safety and security system maintenance', true, true, NOW() - INTERVAL '45 days'),
    ('General Maintenance Co.', 'General Maintenance Co.', 'contact@genmaintenance.com', '0905678901', '0905678902', '654 Fix Street, District 5', 'Ho Chi Minh City', 'Ho Chi Minh', '70000', NULL, 'LIC-2024-005', 'Basic insurance', 'TAX-567890', 4.5, 350000, '0905678903', 'Mon-Sat 7AM-7PM', 200, 1500000, 'General property maintenance and repairs', false, true, NOW() - INTERVAL '30 days');

-- Vendor Specialties
INSERT INTO vendor_specialties (vendor_id, specialty)
SELECT id, 'HVAC' FROM vendors WHERE name = 'TechFix Solutions'
UNION ALL
SELECT id, 'ELECTRICAL' FROM vendors WHERE name = 'TechFix Solutions'
UNION ALL
SELECT id, 'PLUMBING' FROM vendors WHERE name = 'PlumbPro Services'
UNION ALL
SELECT id, 'ELEVATOR' FROM vendors WHERE name = 'Elevator Experts'
UNION ALL
SELECT id, 'FIRE_SAFETY' FROM vendors WHERE name = 'SafeGuard Security'
UNION ALL
SELECT id, 'SECURITY' FROM vendors WHERE name = 'SafeGuard Security'
UNION ALL
SELECT id, 'GENERAL' FROM vendors WHERE name = 'General Maintenance Co.';

-- ============================================
-- PROPERTY AMENITIES
-- ============================================
-- Amenities for Sunset Heights
INSERT INTO property_amenities (property_id, name, description, category, icon, is_available, additional_cost, cost_frequency, location, operating_hours, capacity, booking_required, display_order, created_at, updated_at, is_active)
SELECT 
    (SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
    'Fitness Center',
    'Fully equipped gym with cardio machines, weights, and yoga area',
    'FITNESS',
    'dumbbell',
    true,
    0,
    NULL,
    'Ground Floor, Building A',
    '24/7',
    20,
    false,
    1,
    NOW() - INTERVAL '60 days',
    NOW(),
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
    'Swimming Pool',
    'Outdoor swimming pool with sun deck and lounge chairs',
    'RECREATION',
    'swimming-pool',
    true,
    0,
    NULL,
    'Rooftop',
    '6:00 AM - 10:00 PM',
    50,
    false,
    2,
    NOW() - INTERVAL '60 days',
    NOW(),
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
    'Parking Garage',
    'Underground parking with 24/7 security',
    'PARKING',
    'car',
    true,
    500000,
    'MONTHLY',
    'Basement Level',
    '24/7',
    100,
    false,
    3,
    NOW() - INTERVAL '60 days',
    NOW(),
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
    'Security System',
    '24/7 security with CCTV and access control',
    'SECURITY',
    'shield',
    true,
    0,
    NULL,
    'Entrance and Common Areas',
    '24/7',
    NULL,
    false,
    4,
    NOW() - INTERVAL '60 days',
    NOW(),
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
    'Rooftop Garden',
    'Beautiful rooftop garden with seating area',
    'RECREATION',
    'tree',
    true,
    0,
    NULL,
    'Rooftop',
    '6:00 AM - 9:00 PM',
    30,
    false,
    5,
    NOW() - INTERVAL '60 days',
    NOW(),
    true;

-- Amenities for Urban Lofts
INSERT INTO property_amenities (property_id, name, description, category, icon, is_available, additional_cost, cost_frequency, location, operating_hours, capacity, booking_required, display_order, created_at, updated_at, is_active)
SELECT 
    (SELECT id FROM properties WHERE name = 'Urban Lofts' LIMIT 1),
    'Co-Working Space',
    'Modern co-working space with high-speed internet',
    'OTHER',
    'laptop',
    true,
    200000,
    'MONTHLY',
    '2nd Floor',
    '24/7',
    25,
    true,
    1,
    NOW() - INTERVAL '50 days',
    NOW(),
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Urban Lofts' LIMIT 1),
    'Rooftop Lounge',
    'Stylish rooftop lounge with bar and city views',
    'RECREATION',
    'cocktail',
    true,
    0,
    NULL,
    'Rooftop',
    '5:00 PM - 11:00 PM',
    40,
    true,
    2,
    NOW() - INTERVAL '50 days',
    NOW(),
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Urban Lofts' LIMIT 1),
    'Bike Storage',
    'Secure bike storage area',
    'PARKING',
    'bike',
    true,
    0,
    NULL,
    'Ground Floor',
    '24/7',
    50,
    false,
    3,
    NOW() - INTERVAL '50 days',
    NOW(),
    true;

-- Amenities for Garden Villas
INSERT INTO property_amenities (property_id, name, description, category, icon, is_available, additional_cost, cost_frequency, location, operating_hours, capacity, booking_required, display_order, created_at, updated_at, is_active)
SELECT 
    (SELECT id FROM properties WHERE name = 'Garden Villas' LIMIT 1),
    'Children Playground',
    'Safe playground equipment for children',
    'RECREATION',
    'playground',
    true,
    0,
    NULL,
    'Garden Area',
    '6:00 AM - 8:00 PM',
    20,
    false,
    1,
    NOW() - INTERVAL '40 days',
    NOW(),
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Garden Villas' LIMIT 1),
    'BBQ Area',
    'Outdoor BBQ area with grills and seating',
    'RECREATION',
    'grill',
    true,
    0,
    NULL,
    'Garden Area',
    '5:00 PM - 10:00 PM',
    15,
    true,
    2,
    NOW() - INTERVAL '40 days',
    NOW(),
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Garden Villas' LIMIT 1),
    'Private Garden',
    'Private garden space for each villa',
    'RECREATION',
    'garden',
    true,
    0,
    NULL,
    'Each Villa',
    '24/7',
    NULL,
    false,
    3,
    NOW() - INTERVAL '40 days',
    NOW(),
    true;

-- ============================================
-- PROPERTY IMAGES
-- ============================================
-- Images for Sunset Heights
INSERT INTO property_images (property_id, filename, original_filename, file_path, file_size, mime_type, image_type, is_primary, display_order, caption, alt_text, width, height, uploaded_at, uploaded_by, is_active)
SELECT 
    (SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
    'sunset-heights-exterior-1.jpg',
    'exterior-main.jpg',
    '/uploads/properties/sunset-heights-exterior-1.jpg',
    2048000,
    'image/jpeg',
    'EXTERIOR',
    true,
    1,
    'Main building exterior view',
    'Sunset Heights apartment building exterior',
    1920,
    1080,
    NOW() - INTERVAL '50 days',
    'admin',
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
    'sunset-heights-lobby.jpg',
    'lobby.jpg',
    '/uploads/properties/sunset-heights-lobby.jpg',
    1536000,
    'image/jpeg',
    'INTERIOR',
    false,
    2,
    'Modern lobby area',
    'Sunset Heights lobby',
    1920,
    1080,
    NOW() - INTERVAL '50 days',
    'admin',
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
    'sunset-heights-pool.jpg',
    'pool.jpg',
    '/uploads/properties/sunset-heights-pool.jpg',
    2560000,
    'image/jpeg',
    'AMENITY',
    false,
    3,
    'Rooftop swimming pool',
    'Sunset Heights rooftop pool',
    1920,
    1080,
    NOW() - INTERVAL '50 days',
    'admin',
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
    'sunset-heights-apartment-1.jpg',
    'apartment-sample.jpg',
    '/uploads/properties/sunset-heights-apartment-1.jpg',
    1800000,
    'image/jpeg',
    'INTERIOR',
    false,
    4,
    'Sample apartment interior',
    'Sunset Heights apartment interior',
    1920,
    1080,
    NOW() - INTERVAL '50 days',
    'admin',
    true;

-- Images for Urban Lofts
INSERT INTO property_images (property_id, filename, original_filename, file_path, file_size, mime_type, image_type, is_primary, display_order, caption, alt_text, width, height, uploaded_at, uploaded_by, is_active)
SELECT 
    (SELECT id FROM properties WHERE name = 'Urban Lofts' LIMIT 1),
    'urban-lofts-exterior.jpg',
    'exterior.jpg',
    '/uploads/properties/urban-lofts-exterior.jpg',
    2200000,
    'image/jpeg',
    'EXTERIOR',
    true,
    1,
    'Urban Lofts building exterior',
    'Urban Lofts exterior view',
    1920,
    1080,
    NOW() - INTERVAL '40 days',
    'admin',
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Urban Lofts' LIMIT 1),
    'urban-lofts-loft-interior.jpg',
    'loft-interior.jpg',
    '/uploads/properties/urban-lofts-loft-interior.jpg',
    1900000,
    'image/jpeg',
    'INTERIOR',
    false,
    2,
    'Modern loft interior design',
    'Urban Lofts interior',
    1920,
    1080,
    NOW() - INTERVAL '40 days',
    'admin',
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Urban Lofts' LIMIT 1),
    'urban-lofts-rooftop.jpg',
    'rooftop-lounge.jpg',
    '/uploads/properties/urban-lofts-rooftop.jpg',
    2100000,
    'image/jpeg',
    'AMENITY',
    false,
    3,
    'Rooftop lounge area',
    'Urban Lofts rooftop lounge',
    1920,
    1080,
    NOW() - INTERVAL '40 days',
    'admin',
    true;

-- Images for Garden Villas
INSERT INTO property_images (property_id, filename, original_filename, file_path, file_size, mime_type, image_type, is_primary, display_order, caption, alt_text, width, height, uploaded_at, uploaded_by, is_active)
SELECT 
    (SELECT id FROM properties WHERE name = 'Garden Villas' LIMIT 1),
    'garden-villas-exterior.jpg',
    'villa-exterior.jpg',
    '/uploads/properties/garden-villas-exterior.jpg',
    2400000,
    'image/jpeg',
    'EXTERIOR',
    true,
    1,
    'Garden Villa exterior',
    'Garden Villas exterior',
    1920,
    1080,
    NOW() - INTERVAL '30 days',
    'admin',
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Garden Villas' LIMIT 1),
    'garden-villas-garden.jpg',
    'garden-area.jpg',
    '/uploads/properties/garden-villas-garden.jpg',
    2300000,
    'image/jpeg',
    'AMENITY',
    false,
    2,
    'Beautiful garden area',
    'Garden Villas garden',
    1920,
    1080,
    NOW() - INTERVAL '30 days',
    'admin',
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Garden Villas' LIMIT 1),
    'garden-villas-interior.jpg',
    'villa-interior.jpg',
    '/uploads/properties/garden-villas-interior.jpg',
    2000000,
    'image/jpeg',
    'INTERIOR',
    false,
    3,
    'Spacious villa interior',
    'Garden Villas interior',
    1920,
    1080,
    NOW() - INTERVAL '30 days',
    'admin',
    true;

-- ============================================
-- FLOOR PLANS
-- ============================================
-- Floor Plans for Sunset Heights
INSERT INTO floor_plans (property_id, name, description, filename, original_filename, file_path, file_size, mime_type, floor_number, total_area, area_unit, bedrooms, bathrooms, is_primary, display_order, width, height, scale_ratio, uploaded_at, uploaded_by, is_active)
SELECT 
    (SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
    'Studio Unit - Floor 1',
    'Compact studio unit perfect for single professionals',
    'sunset-studios-floor1.pdf',
    'studio-floor-plan.pdf',
    '/uploads/floor-plans/sunset-studios-floor1.pdf',
    512000,
    'application/pdf',
    1,
    30.0,
    'sqm',
    0,
    1,
    true,
    1,
    2100,
    2970,
    '1:100',
    NOW() - INTERVAL '45 days',
    'admin',
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
    '1 Bedroom Unit - Floor 2-4',
    'Spacious 1 bedroom unit with balcony',
    'sunset-1br-floors2-4.pdf',
    '1br-floor-plan.pdf',
    '/uploads/floor-plans/sunset-1br-floors2-4.pdf',
    640000,
    'application/pdf',
    2,
    45.0,
    'sqm',
    1,
    1,
    false,
    2,
    2100,
    2970,
    '1:100',
    NOW() - INTERVAL '45 days',
    'admin',
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
    '2 Bedroom Unit - Floor 2-4',
    'Large 2 bedroom unit ideal for families',
    'sunset-2br-floors2-4.pdf',
    '2br-floor-plan.pdf',
    '/uploads/floor-plans/sunset-2br-floors2-4.pdf',
    768000,
    'application/pdf',
    2,
    70.0,
    'sqm',
    2,
    2,
    false,
    3,
    2100,
    2970,
    '1:100',
    NOW() - INTERVAL '45 days',
    'admin',
    true;

-- Floor Plans for Urban Lofts
INSERT INTO floor_plans (property_id, name, description, filename, original_filename, file_path, file_size, mime_type, floor_number, total_area, area_unit, bedrooms, bathrooms, is_primary, display_order, width, height, scale_ratio, uploaded_at, uploaded_by, is_active)
SELECT 
    (SELECT id FROM properties WHERE name = 'Urban Lofts' LIMIT 1),
    'Loft Unit - All Floors',
    'Modern loft-style unit with high ceilings',
    'urban-loft-unit.pdf',
    'loft-floor-plan.pdf',
    '/uploads/floor-plans/urban-loft-unit.pdf',
    580000,
    'application/pdf',
    3,
    55.0,
    'sqm',
    1,
    1,
    true,
    1,
    2100,
    2970,
    '1:100',
    NOW() - INTERVAL '35 days',
    'admin',
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Urban Lofts' LIMIT 1),
    'Penthouse Unit - Top Floor',
    'Luxury penthouse with rooftop access',
    'urban-penthouse.pdf',
    'penthouse-floor-plan.pdf',
    '/uploads/floor-plans/urban-penthouse.pdf',
    720000,
    'application/pdf',
    10,
    120.0,
    'sqm',
    3,
    2,
    false,
    2,
    2100,
    2970,
    '1:100',
    NOW() - INTERVAL '35 days',
    'admin',
    true;

-- Floor Plans for Garden Villas
INSERT INTO floor_plans (property_id, name, description, filename, original_filename, file_path, file_size, mime_type, floor_number, total_area, area_unit, bedrooms, bathrooms, is_primary, display_order, width, height, scale_ratio, uploaded_at, uploaded_by, is_active)
SELECT 
    (SELECT id FROM properties WHERE name = 'Garden Villas' LIMIT 1),
    'Villa Type A - 3 Bedrooms',
    'Spacious 3 bedroom villa with garden',
    'garden-villa-3br.pdf',
    'villa-3br-plan.pdf',
    '/uploads/floor-plans/garden-villa-3br.pdf',
    850000,
    'application/pdf',
    1,
    150.0,
    'sqm',
    3,
    3,
    true,
    1,
    2100,
    2970,
    '1:100',
    NOW() - INTERVAL '25 days',
    'admin',
    true
UNION ALL
SELECT 
    (SELECT id FROM properties WHERE name = 'Garden Villas' LIMIT 1),
    'Villa Type B - 4 Bedrooms',
    'Large 4 bedroom villa with private garden',
    'garden-villa-4br.pdf',
    'villa-4br-plan.pdf',
    '/uploads/floor-plans/garden-villa-4br.pdf',
    920000,
    'application/pdf',
    1,
    200.0,
    'sqm',
    4,
    4,
    false,
    2,
    2100,
    2970,
    '1:100',
    NOW() - INTERVAL '25 days',
    'admin',
    true;

-- ============================================
-- MAINTENANCE SCHEDULES
-- ============================================
-- Maintenance Schedules for Sunset Heights
INSERT INTO maintenance_schedules (property_id, vendor_id, title, description, maintenance_type, priority, status, scheduled_date, estimated_duration, estimated_cost, actual_cost, recurrence_type, recurrence_interval, next_due_date, location, special_instructions, tenant_notification_required, access_required, completed_date, completed_by, completion_notes, created_at, updated_at, created_by)
VALUES 
    ((SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
     (SELECT id FROM vendors WHERE name = 'TechFix Solutions' LIMIT 1),
     'Monthly HVAC System Check',
     'Routine inspection and maintenance of all HVAC units',
     'HVAC',
     'MEDIUM',
     'SCHEDULED',
     CURRENT_DATE + INTERVAL '5 days',
     120,
     1500000.0,
     NULL,
     'MONTHLY',
     1,
     CURRENT_DATE + INTERVAL '35 days',
     'All Units',
     'Check filters, clean coils, test thermostat',
     true,
     true,
     NULL,
     NULL,
     NULL,
     NOW() - INTERVAL '20 days',
     NOW(),
     'admin'),
    ((SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
     (SELECT id FROM vendors WHERE name = 'Elevator Experts' LIMIT 1),
     'Quarterly Elevator Inspection',
     'Full elevator safety inspection and maintenance',
     'ELEVATOR',
     'HIGH',
     'SCHEDULED',
     CURRENT_DATE + INTERVAL '15 days',
     240,
     5000000.0,
     NULL,
     'QUARTERLY',
     3,
     CURRENT_DATE + INTERVAL '105 days',
     'Main Elevator',
     'Requires elevator shutdown for 2 hours',
     true,
     false,
     NULL,
     NULL,
     NULL,
     NOW() - INTERVAL '15 days',
     NOW(),
     'admin'),
    ((SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
     (SELECT id FROM vendors WHERE name = 'PlumbPro Services' LIMIT 1),
     'Annual Plumbing System Check',
     'Complete plumbing system inspection and maintenance',
     'PLUMBING',
     'MEDIUM',
     'SCHEDULED',
     CURRENT_DATE + INTERVAL '30 days',
     180,
     3000000.0,
     NULL,
     'YEARLY',
     12,
     CURRENT_DATE + INTERVAL '395 days',
     'All Units and Common Areas',
     'Check all pipes, water pressure, and fixtures',
     true,
     true,
     NULL,
     NULL,
     NULL,
     NOW() - INTERVAL '10 days',
     NOW(),
     'admin'),
    ((SELECT id FROM properties WHERE name = 'Sunset Heights' LIMIT 1),
     (SELECT id FROM vendors WHERE name = 'SafeGuard Security' LIMIT 1),
     'Monthly Fire Safety Check',
     'Inspection of fire alarms, extinguishers, and emergency exits',
     'FIRE_SAFETY',
     'HIGH',
     'COMPLETED',
     CURRENT_DATE - INTERVAL '5 days',
     90,
     2000000.0,
     1800000.0,
     'MONTHLY',
     1,
     CURRENT_DATE + INTERVAL '25 days',
     'All Floors',
     'Test all fire safety equipment',
     false,
     false,
     (NOW() - INTERVAL '5 days')::TIMESTAMP,
     'admin',
     'All systems checked and working properly',
     NOW() - INTERVAL '30 days',
     NOW() - INTERVAL '5 days',
     'admin');

-- Maintenance Schedules for Urban Lofts
INSERT INTO maintenance_schedules (property_id, vendor_id, title, description, maintenance_type, priority, status, scheduled_date, estimated_duration, estimated_cost, actual_cost, recurrence_type, recurrence_interval, next_due_date, location, special_instructions, tenant_notification_required, access_required, completed_date, completed_by, completion_notes, created_at, updated_at, created_by)
VALUES 
    ((SELECT id FROM properties WHERE name = 'Urban Lofts' LIMIT 1),
     (SELECT id FROM vendors WHERE name = 'TechFix Solutions' LIMIT 1),
     'Bi-Annual Electrical System Inspection',
     'Complete electrical system safety inspection',
     'ELECTRICAL',
     'HIGH',
     'SCHEDULED',
     CURRENT_DATE + INTERVAL '20 days',
     300,
     4000000.0,
     NULL,
     'SEMI_ANNUALLY',
     6,
     CURRENT_DATE + INTERVAL '200 days',
     'Electrical Room and All Units',
     'Requires power shutdown coordination',
     true,
     true,
     NULL,
     NULL,
     NULL,
     NOW() - INTERVAL '18 days',
     NOW(),
     'admin'),
    ((SELECT id FROM properties WHERE name = 'Urban Lofts' LIMIT 1),
     (SELECT id FROM vendors WHERE name = 'General Maintenance Co.' LIMIT 1),
     'Weekly Common Area Cleaning',
     'Deep cleaning of common areas and facilities',
     'GENERAL',
     'LOW',
     'SCHEDULED',
     CURRENT_DATE + INTERVAL '2 days',
     120,
     800000.0,
     NULL,
     'WEEKLY',
     1,
     CURRENT_DATE + INTERVAL '9 days',
     'Lobby, Hallways, Elevators',
     'Regular weekly maintenance',
     false,
     false,
     NULL,
     NULL,
     NULL,
     NOW() - INTERVAL '12 days',
     NOW(),
     'admin');

-- Maintenance Schedules for Garden Villas
INSERT INTO maintenance_schedules (property_id, vendor_id, title, description, maintenance_type, priority, status, scheduled_date, estimated_duration, estimated_cost, actual_cost, recurrence_type, recurrence_interval, next_due_date, location, special_instructions, tenant_notification_required, access_required, completed_date, completed_by, completion_notes, created_at, updated_at, created_by)
VALUES 
    ((SELECT id FROM properties WHERE name = 'Garden Villas' LIMIT 1),
     (SELECT id FROM vendors WHERE name = 'General Maintenance Co.' LIMIT 1),
     'Monthly Garden Maintenance',
     'Landscaping, pruning, and garden care',
     'GENERAL',
     'MEDIUM',
     'SCHEDULED',
     CURRENT_DATE + INTERVAL '7 days',
     180,
     2500000.0,
     NULL,
     'MONTHLY',
     1,
     CURRENT_DATE + INTERVAL '37 days',
     'All Garden Areas',
     'Maintain all plants and garden features',
     false,
     false,
     NULL,
     NULL,
     NULL,
     NOW() - INTERVAL '8 days',
     NOW(),
     'admin'),
    ((SELECT id FROM properties WHERE name = 'Garden Villas' LIMIT 1),
     (SELECT id FROM vendors WHERE name = 'PlumbPro Services' LIMIT 1),
     'Quarterly Water System Check',
     'Inspection of water supply and drainage systems',
     'PLUMBING',
     'MEDIUM',
     'SCHEDULED',
     CURRENT_DATE + INTERVAL '25 days',
     150,
     2200000.0,
     NULL,
     'QUARTERLY',
     3,
     CURRENT_DATE + INTERVAL '115 days',
     'All Villas',
     'Check water pressure and drainage',
     true,
     true,
     NULL,
     NULL,
     NULL,
     NOW() - INTERVAL '5 days',
     NOW(),
     'admin');

